### ISSUE TITLE
document uploads - view

### ISSUE THREAD

**Issue by rrd108** [rrd108/sanga#124]
#123 
Jó lenne a view-ben kiírni a file méretét is ha már egyszer úgy is megvan. Meg a user nevét aki létrehozta.

**Comment by Orseolo88** [comment]
A létrehozó csak az a user lehet igaz, akihez a kapcsolat tartozik? így elég csak a contacts_users táblából lekérdezni kiírásnál, vagy inkább tároljam el a documents táblában egy user_id mezőbe pl?

**Comment by rrd108** [comment]
@Orseolo88 a user változhat, ezért le kell tárolni a táblában.

**Comment by Orseolo88** [comment]
Rendben!
