### ISSUE TITLE
password reset 

### ISSUE THREAD

**Issue by moncsybe** [rrd108/sanga#174]
Az emailben küldött link hibára futott az éles rendszeren:
.../users/resetpass/15%2Cpn67K5VzmOLJGwMIucaW4D9Xo1bsr0Fh

Hibaüzenet:
_CakePHP: the rapid development php framework
An Internal Error Has Occurred
Error: An Internal Error Has Occurred._

**Comment by rrd108** [comment]
2016-10-13 08:59:08 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users/resetpass.ctp" is missing.
Request URL: /users/resetpass/15,pn6
