### ISSUE TITLE
Lekérdezés - duplikációk

### ISSUE THREAD

**Issue by moncsybe** [rrd108/sanga#180]
Teszt eset: 
- select: Ismert Név, Hivatalos Név, Csoportok, Város
- szűrés: Hivatalos név: lakatos, Város: Bu

A duplikáció oka valószínűleg az, hogy az union miatt több oldalról is megtalálja ugyanazt a kontaktot --> saját kontakt, saját csoporthoz tartozó kontakt, illetve usercsoport useréhez tartozó kontakt

**Comment by rrd108** [comment]
a $contain tartalmazta a $belongsToMany-ben lévő táblákat is, emiatt volt duplikáció
