### ISSUE TITLE
Kapcsolat felvitel - blokkositas

### ISSUE THREAD

**Issue by moncsybe** [rrd108/sanga#187]
Vannak olyan blokkok, melyekre egyik-masik osztalynak nincs szukseg. Pl. a predikalo osztalynak a munkahelyi informaciokra. 
Altalanos megoldaskent az egyes blokkok ki-becsukhatoak lennenek, es cookieban lenne eltarolva, hogy az adott user az egyes blokkakat milyen allapotban szeretne.

**Comment by rrd108** [comment]
Tegyünk már be egy kis pilinszkát (pl valami le-fel mutató kis háromszöget html dingbat? ▵▿) amire kattintva ki-be lehet csukni a cuccot úgy hogy a cursor pointerre vált. Így most nem látszik, hogy ez itt tud ilyet.
