### ISSUE TITLE
Eletkor kezelese

### ISSUE THREAD

**Issue by moncsybe** [rrd108/sanga#191]
Jelenleg pontos szuletesi datumot var, ami bizonyos esetekben szukseges is, hogy szemelyes szuletesnapi meghivo mehessen ki, vagy fel lehessen venni a kapcsolatot.
Ugyanakkor pl. a predikalo osztaly nem minden esetben tudja a pontos datumot, viszont fontos lenne neki, hogy hany eves.

**Comment by rrd108** [comment]
DATE mező van jelebleg, ebbe nem lehet csak évet rögzíteni

**Comment by rrd108** [comment]
varchar + html pattern
