### ISSUE TITLE
Plusz mező - helyszín

### ISSUE THREAD

**Issue by moncsybe** [rrd108/sanga#213]
Fontos lenne nem csak azt tudni, hogy melyik településen él, hanem hogy melyik nagyváros, vagy náma-hatta közelében, hogy pl. a szegedi programra ne csak a szegedieket, hanem a környékbelieket is meg tudjuk hívni. Lehet, hogy 2 mező is lehetne, egyik a nagyvárosnak, egy másik meg a náma-hattának - ez utóbbihoz egy legördülő lista lenne a legjobb.

**Comment by rrd108** [comment]
A keresésben lesz majd egy olyan, hogy x km-es körzetben keressen. Ez kiszolgálja majd ezt az igényt.
