### ISSUE TITLE
Kontakt keresés

### ISSUE THREAD

**Issue by moncsybe** [rrd108/sanga#225]
Az oldal tetején lévő kereső nem működik pl. ű betűre - lehet, hogy ő betűre sem. 
Pl. Szűcs Tamás névre nem lehet keresni. 
(email alapján lehetett csak visszakeresni thomasherczeg...)

**Comment by rrd108** [comment]
A birth mezőben is keresett, de ez nem szereti a LIKE operátort MYSQL-ben
