### ISSUE TITLE
Export - Csoportok nem kerülnek bele

### ISSUE THREAD

**Issue by moncsybe** [rrd108/sanga#230]
A lekérdezésnél hiába történik meg a csoportok lista, az exportba nem kerül bele. 
Most, hogy elkezdjük az online kurzusokat, erre SOS szükségünk lenne. Az lenne az igazi, ha az egyes csoportnevek pontosvesszővel lennének elválasztva.

**Comment by rrd108** [comment]
pontosítást kérek, nem tudom reprodukálni

**Comment by moncsybe** [comment]
Most néztem bekerül az újabb exportokba, úgy látszik megjavult :) Már csak arra lenne szükség, hogy az egyes csoport nevek pontosvesszővel legyenek elválasztva, ha megoldható.

**Comment by rrd108** [comment]
fixed 3ebb165136be1b74469bcd56085b07f1c5fb8d77
