### ISSUE TITLE
Contacts/view

### ISSUE THREAD

**Issue by rrd108** [rrd108/sanga#49]
hide inputs
make nice design

**Comment by rrd108** [comment]
@admdh The tabs what are now vertical could be horizontal. By this we could save place for the main thing. Tabs now done by http://jqueryui.com/tabs/

**Comment by admdh** [comment]
due mobile and same user experience better to stay with vertical menu.

and this is one of the reasons why design should be done first, so we had picture what to do before start to work with code. it's much easier keep work organised and cleaner code.

**Comment by rrd108** [comment]
@admdh  I like what you made. Now this is my part :-)
