### ISSUE TITLE
login

### ISSUE THREAD

**Issue by rrd108** [rrd108/sanga#50]
nice design

**Comment by admdh** [comment]
hot to delete header on login page?
i think there should also be forgot  password link..

**Comment by rrd108** [comment]
@admdh Why should we delete the header on login page? I already removed the menus, just the logo is there, I like it.

Yes plase add a forgotten pass link there

**Comment by rrd108** [comment]
4f846514bab55d19d04dd7e293aba8afde097364

**Comment by rrd108** [comment]
@admdh forgotten pass link is still missing and header is not as height as after login
