### ISSUE TITLE
attachements for contacts

### ISSUE THREAD

**Issue by rrd108** [rrd108/sanga#62]
erkölcsi, jelentkezési lapok stb

**Comment by Orseolo88** [comment]
A file-t adatbázisban vagy file-rendszerben kellene inkább tárolni?

**Comment by rrd108** [comment]
@Orseolo88 szerintem a DB jobb megközelítés lenne ebben az esetben. Könnyebb lenne a fileok karbantartása, a feleslegesek eltávolítása, a backup, stb.

**Comment by Orseolo88** [comment]
Az Admin menübe készítenék egy almenüt, ahol létre lehetne hozni a feltölthető dokumentum típusokat , úgy mint pl. a Units rész. Ehhez létrehoznék egy documenttypes táblát a következő szerkezettel: id, name.
A Contacts/view részben oldalsó menünek betennék egy Dokumentumok menüpontot. Itt meg lehetne jeleníteni a már feltöltött dokumentumokat, valamint új dokumentumot is hozzá lehetne adni.
A dokumentumokat a fentiek szerint adatbázisban tárolnám. Pl. egy documents nevű tábla az alábbi szerkezettel:
id, contact_id, document_type_id, file_type, size, data (MEDIUMBLOB), created, modified

**Comment by rrd108** [comment]
@Orseolo88 Nem hiszem, hogy szükség lesz típusokra. A másik része ok. jó lenne ha a feltöltött doksik szépen, ikonokkal, amolyan intéző szerűen jelennének meg.

**Comment by Orseolo88** [comment]
Rendben! Akkor még egy document_name mezőt is bevezetnék, hogy be lehessen írni a dokumentum nevét, pl. "Jelentkezési lap"
